[project]
name = "fastapi-backend"
version = "0.2.0" # 与 api/main.py 中的版本一致
description = "FastAPI backend for Stock Valuation App"
requires-python = ">=3.10, <3.11" # 指定Python 3.10
dependencies = [
    "numpy",
    "pandas",
    "SQLAlchemy",
    "psycopg2-binary",
    "python-dotenv",
    "fastapi",
    "uvicorn[standard]",
    "httpx",
    "openai", # For LLM calls
    "tushare",  # For data fetching
    "pyarrow"  # For pandas.to_feather/read_feather
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "flake8",
    "pre-commit"
]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
select = ["E", "W", "F", "I", "UP", "PL", "PT", "RUF"] # Example: select a base set of rules
ignore = ["E501"] # ignore line too long, black will handle it

# If you want uv to manage the Python version for the project's virtual environment:
# [tool.uv]
# python-version = "3.10"
